"""
Check that `lbm3d-perm` is covariant under a permutation of the coordinate axes.

    python scripts/rotation_covariance3d.py                    # 40^3, all 5 permutations
    python scripts/rotation_covariance3d.py --size 32 --perms yxz
    python scripts/rotation_covariance3d.py --structure DATA/aniso3d_pilot/structures/x.raw
    python scripts/rotation_covariance3d.py --self-test        # no solver needed

Why this test exists (NOTES 8.6).  Relabelling the axes of the grid is exact and
lossless — no interpolation, no resampling, not a single voxel changes value —
so the permeability tensor of the permuted structure must be the permuted
tensor, K' = P K P^T, to within roundoff.  Nothing else in the suite covers this:

  * **Reciprocity (K = K^T) does not.**  An index bug that is symmetric under
    transpose passes it.  The measured residuals are ~1e-8, beautiful and
    uninformative here.
  * **The tensor test does not either.**  Stokes flow is linear in F and all
    three solves stop at the same step, so superposition satisfies the (1,1,1)
    prediction even on a field that is consistently mis-indexed.  It validates
    the assembly, not the axis labelling.

The three headline 3D targets are the off-diagonals `k_xy`, `k_xz`, `k_yz`, so
until this passes the three-solve assembly is unverified.  Covariance is a
property of the index logic and not of the domain size, so 40^3 is enough and
costs ~100 s per permutation instead of ~25 min at 80^3.

What "must" means numerically.  D3Q19, the BGK collision and Guo forcing are all
invariant under axis permutations, and the convergence test compares a max over
components against `eps * ||q||`, both permutation-invariant — so the permuted
run stops at the *same step* on the *same* fixed point.  The only difference is
the order in which the flux mean is summed over memory, i.e. double roundoff.
Expect a residual near 1e-12 relative to the trace, four orders below the
solver's own reciprocity floor.  A real index bug is an O(1) effect, not a
marginal one: there is no grey zone here, which is why the default tolerance can
sit at 1e-6 without being either strict or lax.

**The test is only as good as the structure it runs on.**  Compare K' with
P K P^T on a structure whose K is nearly isotropic and it passes for free, since
P K P^T is then K itself.  So the script also reports the *discriminating scale*
— how far P K P^T sits from K — and fails a permutation whose scale is too small
to have proved anything, rather than reporting a vacuous pass.  A strong-stratum
structure is generated by default for this reason.

Not covered: the domain is cubic, so a bug that confuses nx/ny/nz survives this
test.  It also cannot affect the study, whose structures are cubic too; the
Python side of that convention is checked by `structure_io3d.py --self-test`,
which is deliberately non-cubic.
"""

import argparse
import itertools
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from structure_io3d import load_structure, save_structure, porosity   # noqa: E402
import gen_aniso_structures3d as gen                                  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
DEFAULT_SOLVER = REPO / "LMB3d" / "lbm3d-perm"
AXES = "xyz"

# sigma[a] = the OLD solver axis that becomes NEW axis a, so the label reads as
# the old axis names in new-axis order: "yzx" means new x is old y.
PERMS = {"".join(AXES[s] for s in sigma): sigma
         for sigma in itertools.permutations(range(3))}
IDENTITY = (0, 1, 2)


def permute_structure(arr, sigma):
    """
    Relabel the solver axes of a structure array.

    `arr` is indexed [z, y, x] as `structure_io3d` returns it; `sigma` is in
    solver-axis order.  Transposing to [x, y, z] first and back afterwards keeps
    the permutation written the way it is reasoned about, at the price of two
    no-op transposes on a view.
    """
    a = arr.transpose(2, 1, 0)              # [z,y,x] -> [x,y,z]
    a = a.transpose(sigma)                  # new axis a <- old axis sigma[a]
    return np.ascontiguousarray(a.transpose(2, 1, 0))     # -> [z,y,x]


def inverse(sigma):
    inv = [0, 0, 0]
    for a, s in enumerate(sigma):
        inv[s] = a
    return tuple(inv)


def read_K(csv_path):
    """The full (unsymmetrised) K and the row it came from. K[r][c]: flux r, force c."""
    row = pd.read_csv(csv_path).iloc[-1]
    K = np.array([[row[f"K_{r}{c}"] for c in AXES] for r in AXES], float)
    return K, row


def expected(K, sigma):
    """P K P^T, i.e. K'_ab = K_{sigma[a] sigma[b]}."""
    return K[np.ix_(sigma, sigma)]


# ---------------------------------------------------------------------------
# Solver-free checks
# ---------------------------------------------------------------------------

def self_test():
    ok = True

    def check(label, cond):
        nonlocal ok
        ok = ok and bool(cond)
        print(f"[{'ok' if cond else 'FAIL'}] {label}")

    rng = np.random.default_rng(0)
    # non-cubic, so a permutation that only swaps equal axes cannot hide
    arr = (rng.random((5, 7, 11)) > 0.5).astype(np.uint8)     # [z,y,x]
    nx, ny, nz = 11, 7, 5

    for label, sigma in PERMS.items():
        p = permute_structure(arr, sigma)
        want_shape = tuple(np.array([nx, ny, nz])[list(sigma)][::-1])
        check(f"{label}: shape {p.shape} == {want_shape}", p.shape == want_shape)
        check(f"{label}: porosity preserved",
              abs(porosity(p) - porosity(arr)) < 1e-15)
        check(f"{label}: sigma-inverse round-trips",
              np.array_equal(permute_structure(p, inverse(sigma)), arr))

        # the voxel identity itself: new (x,y,z) must hold old coords j with
        # j[sigma[a]] = i[a].  Checked on every voxel, not a sampled few.
        src = arr.transpose(2, 1, 0)
        got = p.transpose(2, 1, 0)
        idx = np.indices(got.shape)                       # idx[a] = i_a
        j = [None] * 3
        for a, s in enumerate(sigma):
            j[s] = idx[a]
        check(f"{label}: every voxel maps to old coords",
              np.array_equal(got, src[tuple(j)]))

    # A permutation of the tensor must undo itself the same way.
    K = rng.random((3, 3))
    for label, sigma in PERMS.items():
        check(f"{label}: expected() inverts",
              np.array_equal(expected(expected(K, sigma), inverse(sigma)), K))

    print("\nself-test", "PASSED" if ok else "FAILED")
    return 0 if ok else 1


# ---------------------------------------------------------------------------
# The real thing
# ---------------------------------------------------------------------------

def make_structure(size, seed, out_dir):
    """
    One strong-stratum structure, chosen for the largest axis ratio among a few
    draws.  A near-isotropic K makes the whole comparison vacuous (see module
    docstring), and the stratum is the only handle on that available before the
    solver has run.
    """
    gen._init_worker(size)
    cfg = {"structures_dir": str(out_dir), "seed": seed,
           "k0_min": 3.0, "k0_max": 7.0, "dk": 1.0,
           "modes_min": 20, "modes_max": 80,
           "por_min": 0.65, "por_max": 0.90, "max_attempts": 200}
    best = None
    for i in (2, 5, 8):                        # sample_id % 3 == 2 is "strong"
        r = gen.gen_one(i, cfg)
        if r is not None and (best is None or r["aniso_A"] > best["aniso_A"]):
            best = r
    if best is None:
        sys.exit("could not generate a percolating structure")
    print(f"structure  {best['filename']}\n"
          f"           A={best['aniso_A']:.2f} B={best['aniso_B']:.2f} "
          f"porosity={best['porosity']:.4f}")
    return out_dir / best["filename"]


def main():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--solver", default=str(DEFAULT_SOLVER))
    p.add_argument("--structure", help="use this .raw instead of generating one")
    p.add_argument("--size", type=int, default=40, help="cubic edge when generating")
    p.add_argument("--seed", type=int, default=7)
    p.add_argument("--perms", nargs="+", default=None,
                   help=f"which permutations to run (default: all of "
                        f"{sorted(k for k in PERMS if PERMS[k] != IDENTITY)})")
    p.add_argument("--tol", type=float, default=1e-6,
                   help="max |K' - P K P^T| / trace(K) accepted")
    p.add_argument("--min-scale", type=float, default=1e-3,
                   help="a permutation whose discriminating scale is below this "
                        "proves nothing and is reported as a failure")
    p.add_argument("--max-steps", type=int, default=200000)
    p.add_argument("--eps", type=float, default=1e-5)
    p.add_argument("--workers", type=int, default=6)
    p.add_argument("--keep", action="store_true", help="keep the working directory")
    p.add_argument("--self-test", action="store_true", dest="selftest")
    a = p.parse_args()

    if a.selftest:
        raise SystemExit(self_test())

    if not Path(a.solver).exists():
        sys.exit(f"solver not found: {a.solver}\n"
                 f"build it with:  cd LMB3d && bash make_perm.sh")

    labels = a.perms or [k for k, s in PERMS.items() if s != IDENTITY]
    bad = [l for l in labels if l not in PERMS]
    if bad:
        sys.exit(f"not a permutation of xyz: {bad}")

    tmp = Path(tempfile.mkdtemp(prefix="rotcov3d_"))
    print(f"solver     {a.solver}")
    print(f"workdir    {tmp}")

    src = Path(a.structure) if a.structure else make_structure(a.size, a.seed, tmp)
    arr = load_structure(src)
    print(f"domain     {arr.shape[2]}x{arr.shape[1]}x{arr.shape[0]} "
          f"(x,y,z)  porosity {porosity(arr):.6f}\n")

    # Write every variant first, including the identity: the reference goes
    # through the same write/read path as the rest, so a bug in this script's
    # own permutation cannot be mistaken for one in the solver.
    jobs = []
    for label in ["xyz"] + [l for l in labels if l != "xyz"]:
        raw = tmp / f"perm_{label}.raw"
        save_structure(raw, permute_structure(arr, PERMS[label]))
        jobs.append((label, raw, tmp / f"perm_{label}.csv"))

    print(f"solving {len(jobs)} orientations, {a.workers} at a time "
          f"({len(jobs) * 3} solves total)")
    running, done = [], []
    while jobs or running:
        while jobs and len(running) < a.workers:
            label, raw, csv = jobs.pop(0)
            proc = subprocess.Popen(
                [a.solver, str(raw), str(csv), "--quiet",
                 "--max-steps", str(a.max_steps), "--eps", str(a.eps)],
                stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
            running.append((label, csv, proc))
        label, csv, proc = running.pop(0)
        _, err = proc.communicate()
        done.append((label, csv, proc.returncode, err.decode().strip()))
        print(f"  {label} done (exit {proc.returncode})")

    results = dict()
    for label, csv, rc, err in done:
        if not csv.exists():
            sys.exit(f"{label}: solver wrote no CSV (exit {rc}) {err}")
        results[label] = read_K(csv)

    K0, row0 = results["xyz"]
    trace = float(np.trace(K0))
    print(f"\nreference K (trace {trace:.6f}, recip_resid {row0.recip_resid:.1e}, "
          f"steps {int(row0.steps_fx)}/{int(row0.steps_fy)}/{int(row0.steps_fz)})")
    for r in range(3):
        print("   [ " + "  ".join(f"{K0[r][c]:12.8f}" for c in range(3)) + " ]")

    print(f"\n{'perm':>6} {'steps x/y/z':>20} {'resid':>10} {'scale':>10} "
          f"{'resid/scale':>12}")
    print("-" * 64)
    ok = True
    for label in [l for l in labels if l != "xyz"]:
        sigma = PERMS[label]
        K, row = results[label]
        want = expected(K0, sigma)
        resid = float(np.abs(K - want).max()) / trace
        # how far the permutation moves K at all: if this is ~0, agreement is
        # automatic and the run has tested nothing.
        scale = float(np.abs(K0 - want).max()) / trace
        steps = f"{int(row.steps_fx)}/{int(row.steps_fy)}/{int(row.steps_fz)}"
        good = resid < a.tol and scale >= a.min_scale
        ok &= good
        note = "" if scale >= a.min_scale else "  <- vacuous, K too isotropic"
        print(f"{label:>6} {steps:>20} {resid:10.2e} {scale:10.2e} "
              f"{resid / scale if scale else float('nan'):12.2e}  "
              f"[{'ok' if good else 'FAIL'}]{note}")
        if not good and scale >= a.min_scale:
            print(f"       measured K' vs expected P K P^T:")
            for r in range(3):
                print("        [ " + "  ".join(f"{K[r][c]:12.8f}" for c in range(3))
                      + " ]   [ "
                      + "  ".join(f"{want[r][c]:12.8f}" for c in range(3)) + " ]")

    # A permuted run that stopped at a different step would explain a residual
    # without any bug being present, so say so rather than leaving it implied.
    ref_steps = (row0.steps_fx, row0.steps_fy, row0.steps_fz)
    for label in [l for l in labels if l != "xyz"]:
        _, row = results[label]
        want = tuple(np.array(ref_steps)[list(PERMS[label])])
        if tuple((row.steps_fx, row.steps_fy, row.steps_fz)) != want:
            print(f"\nnote: {label} converged at different steps than the "
                  f"reference ({want} expected) — the residual above is then "
                  f"a convergence difference, not necessarily an index bug")

    if not a.keep:
        for f in tmp.iterdir():
            f.unlink()
        tmp.rmdir()
    else:
        print(f"\nkept {tmp}")

    print("\nrotation covariance", "PASSED" if ok else "FAILED")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
